---
title: "Modified_t"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(MASS)
library(ggplot2)
library(dplyr)
library(tidyr)
library(SpatialPack)
```


```{r}
SAT <- function (Beta=0, rangeE = 1.5, rangeR = 2.5, psill = 0.05, Nsimulation =10, Nrow = 5, Ncol = 5, deterministic = "Random", Nsample =50){
  Random_N = 0 #The number of tests
  Random_S = 0 #The number of times when p is less than 0.05
  Systematic_N = 0
  Systematic_S = 0
  Vertical_N = 0
  Vertical_S = 0
  #TwoVertical_N = 0
  #TwoVertical_S = 0
  P_values <- c()
  
  
  for(i in 1:Nsimulation){
    xy <- expand.grid(1:Nrow, 1:Ncol)
    names(xy) <- c('x', 'y')
    distance <- as.matrix(dist(xy, method = "euclidean"))
    npoints <- nrow(xy)
    
    #simulating ckfkfkfkfk values
    D<- switch(deterministic, "Random" = rep(0, npoints),"XYgradient" = 1.5*xy[,1]+1.5*xy[,2], "Two Zone" = c(rep(10, npoints/2),rep(2,npoints/2))) # defining deterministic. Random means there is no deterministic. XYgradient is linear gradients from north to south and from west to east. 
    
    muE <- D ## mu for Explanatory variable
    SAE <- mvrnorm(1, mu = muE, Sigma = psill*exp(-distance/rangeE)+diag(x = 0.4, nrow=Nrow*Ncol, ncol = Nrow*Ncol)) # simulating data for explanatory variable 
    
    #simulating response values
    muR <- Beta*SAE ## mu for response 
    SAR<- mvrnorm(1, mu = muR, Sigma = psill * exp(-distance / rangeR)+diag(x = 0.4, nrow =Nrow*Ncol, ncol = Nrow*Ncol ))
    
    
    ## Sample SAE for Random sampling 
    Random_sampleSAE = sample_n(data.frame(SAE), size = Nsample, replace = FALSE)
    ## SAR
    Random_sampleSAR = data.frame(SAR)[row.names(Random_sampleSAE),]
    ## coordinates for adjusted test
    Random_coords <- xy[c(rownames(Random_sampleSAE)),]
    Random_p <- modified.ttest(Random_sampleSAE[,1], Random_sampleSAR, Random_coords)$p.value
    
    if(0.05>= Random_p){
      Random_S = Random_S+ 1
    }
    Random_N = Random_N+1 
    
    ## Sampling SAE for systematic 
    Systematic_sampleSAE = SAE[seq(1, length(SAE), npoints/Nsample)]
    Systematic_sampleSAR = SAR[seq(1, length(SAR), npoints/Nsample)]
    Systematic_coords <- xy[c(names(Systematic_sampleSAE)),]
    
    Systematic_p <- modified.ttest(Systematic_sampleSAE, Systematic_sampleSAR, Systematic_coords)$p.value
    if(Systematic_p <= 0.05){
      Systematic_S = Systematic_S+1
      
    }
    Systematic_N = Systematic_N+1
    
    col <- sample(1:Ncol, 1)
    start <- Nrow*col-Nrow+1 ## starting index
    last <- Nrow*col ## ending index
    # Interval of 2, sampling every other point
    
    Vertical_sampleSAE <- SAE[start:last][seq(1, length(SAE[start:last]), 2)]
    Vertical_sampleSAR  <- SAR[start:last][seq(1, length(SAR[start:last]), 2)]
    
    Vertical_Nsample <- Ncol/2
    
    Vertical_coords <- xy[names(Vertical_sampleSAE),]
    #print(xy[names(Vertical_sampleSAE),])
    #print(Vertical_sampleSAE)
    
    Vertical_p <- modified.ttest(Vertical_sampleSAE, Vertical_sampleSAR, Vertical_coords)$p.value
    #print(modified.ttest(Vertical_sampleSAE, Vertical_sampleSAR, Vertical_coords))
    if(0.05>= Vertical_p){
      Vertical_S = Vertical_S +1  ## if p is less than 0.05, increment S by 1
    }
    
    Vertical_N = Vertical_N+1
    
   
    
    
   
    
    
    
    
    print(i)
  }
  
  
  
  output <- list(Random_S/Random_N,Systematic_S/Systematic_N ,Vertical_S/Vertical_N, rangeE, rangeR)
  names(output) <- c("Sampling_Random","Sampling_Systematic","Sampling_Vertical","rangeE", "rangeR")
  output
}




## In the paper, we have total of 9 combinations for variogram ranges. They use 0, 20, and 50. 
rangeEvec = c(0.0000001, 3, 5) ## Variogram ranges for E
rangeRvec = c(0.0000001, 3, 5) ## Variaogram ranges for R

params <- expand.grid(rangeEvec, rangeRvec)

names(params) <- c('rangeE', 'rangeR') ## All combinations of variogram ranges. For the future, we are going to add sampling designs in the params vectors. 
Results_total<-data.frame()## empty dataframe. Use this dataframe to add proportion later. 

SAT(Beta=0, rangeE = 3, rangeR = 3, psill = 0.3, Nsimulation =500, Nrow = 30, Ncol =30, deterministic = "Random", Nsample = 100)

for(i in 1:nrow(params)){
  
  Result <-data.frame(SAT(Beta=0, rangeE = params[i, 1], rangeR = params[i, 2], psill = 0.3, Nsimulation =500, Nrow = 12, Ncol =12, deterministic = "Random", Nsample = 100)) ## new datarame for each function call. 
  Results_total<-rbind(Result, Results_total)## Add new dataframe to total results
  print(i)
}


Results_total<- 
  Results_total %>%
  pivot_longer(
    cols = starts_with("Sampling"),
    names_to = "Sampling",
    values_to = "Proportion",
    values_drop_na = TRUE
  )

ggplot(data=Results_total, aes(x=rangeR, y=Proportion, group=Sampling)) +
  geom_line(aes(linetype=Sampling))+
  geom_point()+
  facet_grid(. ~ rangeE)


```



```{r}
Vertical_coords <- xy[names(Vertical_sampleSAE),]
    
    Vertical_p <- modified.ttest(Vertical_sampleSAE, Vertical_sampleSAR, Vertical_coords)$p.value
```
```

