---
title: "TestSummary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First Simulation 
Setting: Deterministic = 0 (Random), Beta = 0, Nsimulation = 250, Nrow = 34, Ncol = 34, Nsample = 100, rangeE = ( 0.000001, 6, 13), rangeR = ( 0.000001, 6, 13)

Type 1 error: 
The rate of type 1 error is inflated when autocorrelation is present in both variables, Basically the rate is highest when rangeE = 13 and rangeR = 13. If one of the autocorrelations or ranges is not present, the rate of error is low. Random, systematic, stratified sampling shows this trend but vertical, and two vertical samling methods did not show this trend. I am guessing it is because of the small sampling size of 34/2. Dutilleul modified t-test successfully corrected the rate of type 1 error with all the sampling methods. 

Power:

Power does not change depending on the samplin design. For random, systematic, and stratified sampling, the power stayed around 0.8. While the power is around 0.2 for vertical and two vertical sampling design. I am guessig this difference is due to the sampling size (100 for random, systematic, and stratified, 17 for vertical and two vertical). In most of the cases, unmodified t-test has higher power compared to the power calculated by the modified t test. This is also in accord with the paper. The author explains that the greater power of the unmodified t-test is due to the increase in rate of type 1 error. When the unmodified t-test has the correct rate of type 1 error, the power is about the same as the modified t-test. The presence of SA in response seems to reduce the power. 